# Generated by Django 2.1.2 on 2019-02-22 00:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('subject', models.TextField(max_length=500)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=17)),
                ('label', models.CharField(max_length=100)),
                ('blurb', models.CharField(max_length=500, null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('font_color', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(max_length=35, null=True)),
                ('last_name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('PA', 'Pennsylvania'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('RI', 'Rhode Island'), ('SC', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='PA', max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('municipality', models.CharField(choices=[('PHILADELPHIA', 'Philadelphia, PA'), ('LOWER_MERION', 'Lower Merion Township, PA'), ('NARBERTH', 'Narberth, PA'), ('RADNOR', ', Radnor Township, PA'), ('HAVERFORD', ', Haverford Township, PA'), ('WILLISTOWN', 'Willistown Township, PA'), ('EASTTOWN', ', Easttown Township, PA'), ('MALVERN', ', Malvern, PA'), ('PITTSBURGH', ', Pittsburgh, PA'), ('TREDYFFRIN', 'Tredyffrin Township, PA'), ('NEW_YORK', 'New York, NY'), ('LOS_ANGELES', 'Los Angeles, CA'), ('CHICAGO', 'Chicago, IL'), ('HOUSTON', 'Houston, TX'), ('PHOENIX', 'Phoenix, AZ'), ('SAN_ANTONIO', 'San Antonio, TX'), ('SAN_DIEGO', 'San Diego, CA'), ('DALLAS', 'Dallas, TX'), ('SAN_JOSE', 'San Jose, CA'), ('AUSTIN', 'Austin, TX'), ('INDIANAPOLIS', 'Indianapolis, IN'), ('JACKSONVILLE', 'Jacksonville, FL'), ('SAN_FRANCISCO', 'San Francisco, CA'), ('COLUMBUS', 'Columbus, OH'), ('CHARLOTTE', 'Charlotte, NC'), ('FORT_WORTH', 'Fort Worth, TX'), ('DETROIT', 'Detroit, MI'), ('EL_PASO', 'El Paso, TX'), ('MEMPHIS', 'Memphis, TN'), ('SEATTLE', 'Seattle, WA'), ('DENVER', 'Denver, CO'), ('DC', 'Washington, DC'), ('BOSTON', 'Boston, MA'), ('NASHVILLE', 'Nashville, TN'), ('BALTIMORE', 'Baltimore, MD'), ('NEWTON', 'Newton, MA'), ('BROOKLINE', 'Brooline, MA'), ('CAMBRIDGE', 'Cambridge, MA'), ('NAPERVILLE', 'Naperville, IL'), ('WHITE_PLAINS', 'White Plains, NY'), ('NEW_HAVEN', 'New Haven, CT'), ('STAMFORD', 'Stamford, CT'), ('PRINCETON', 'Princeton, NJ')], max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('carrier', models.CharField(choices=[('VER', 'Verizon Wireless'), ('ATT', 'AT&T Mobility'), ('SPR', 'Sprint Corporation'), ('TMO', 'T-Mobile US'), ('USC', 'US Cellular'), ('VRG', 'Virgin Mobile')], max_length=3)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('payment_method', models.CharField(choices=[('CSH', 'Cash'), ('CHK', 'Check'), ('VEN', 'Venmo'), ('CRD', 'Card'), ('CMP', 'Comped')], max_length=3)),
                ('expense_date', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(max_length=35, null=True)),
                ('last_name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('PA', 'Pennsylvania'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('RI', 'Rhode Island'), ('SC', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='PA', max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('municipality', models.CharField(choices=[('PHILADELPHIA', 'Philadelphia, PA'), ('LOWER_MERION', 'Lower Merion Township, PA'), ('NARBERTH', 'Narberth, PA'), ('RADNOR', ', Radnor Township, PA'), ('HAVERFORD', ', Haverford Township, PA'), ('WILLISTOWN', 'Willistown Township, PA'), ('EASTTOWN', ', Easttown Township, PA'), ('MALVERN', ', Malvern, PA'), ('PITTSBURGH', ', Pittsburgh, PA'), ('TREDYFFRIN', 'Tredyffrin Township, PA'), ('NEW_YORK', 'New York, NY'), ('LOS_ANGELES', 'Los Angeles, CA'), ('CHICAGO', 'Chicago, IL'), ('HOUSTON', 'Houston, TX'), ('PHOENIX', 'Phoenix, AZ'), ('SAN_ANTONIO', 'San Antonio, TX'), ('SAN_DIEGO', 'San Diego, CA'), ('DALLAS', 'Dallas, TX'), ('SAN_JOSE', 'San Jose, CA'), ('AUSTIN', 'Austin, TX'), ('INDIANAPOLIS', 'Indianapolis, IN'), ('JACKSONVILLE', 'Jacksonville, FL'), ('SAN_FRANCISCO', 'San Francisco, CA'), ('COLUMBUS', 'Columbus, OH'), ('CHARLOTTE', 'Charlotte, NC'), ('FORT_WORTH', 'Fort Worth, TX'), ('DETROIT', 'Detroit, MI'), ('EL_PASO', 'El Paso, TX'), ('MEMPHIS', 'Memphis, TN'), ('SEATTLE', 'Seattle, WA'), ('DENVER', 'Denver, CO'), ('DC', 'Washington, DC'), ('BOSTON', 'Boston, MA'), ('NASHVILLE', 'Nashville, TN'), ('BALTIMORE', 'Baltimore, MD'), ('NEWTON', 'Newton, MA'), ('BROOKLINE', 'Brooline, MA'), ('CAMBRIDGE', 'Cambridge, MA'), ('NAPERVILLE', 'Naperville, IL'), ('WHITE_PLAINS', 'White Plains, NY'), ('NEW_HAVEN', 'New Haven, CT'), ('STAMFORD', 'Stamford, CT'), ('PRINCETON', 'Princeton, NJ')], max_length=25)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('credit', models.BooleanField(default=True)),
                ('non_cash', models.BooleanField(default=True)),
                ('cancelled', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('expense_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bread.Expense')),
            ],
        ),
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=17)),
                ('label', models.CharField(max_length=100)),
                ('super_cat', models.CharField(choices=[('DRY', 'Dry ingredients'), ('OIL', 'Honey, syrups, chocolate and oils'), ('DAIRY', 'Eggs and dairy'), ('SEASON', 'Seasoning and spices'), ('FRUITS', 'Fruits, nuts and seeds'), ('PACK', 'Packaging')], default='DRY', max_length=6)),
                ('display_order', models.IntegerField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=17)),
                ('label', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('measure', models.CharField(choices=[('WT', 'weight'), ('VOL', 'volume'), ('CT', 'count'), ('LEN', 'length')], max_length=6)),
                ('units', models.CharField(max_length=6, null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bread.MaterialCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('delivery_date', models.DateField(default=datetime.date(2019, 2, 25))),
                ('order_date', models.DateTimeField()),
                ('standing', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, max_length=150, null=True)),
                ('this_is_a_gift', models.BooleanField(default=False)),
                ('meister', models.BooleanField(default=False)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_address', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_city', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_state', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_message', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CSH', 'Cash'), ('CHK', 'Check'), ('VEN', 'Venmo'), ('CRD', 'Card'), ('CMP', 'Comped')], max_length=3)),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=17)),
                ('label', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bread.Category')),
            ],
        ),
        migrations.CreateModel(
            name='StripeCharge',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('charge_id', models.CharField(max_length=234)),
                ('payment_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bread.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(max_length=35, null=True)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=100)),
                ('is_subscriber', models.BooleanField(default=True)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('challah_freq', models.CharField(choices=[('WEEK', 'Weekly'), ('2_WKS', 'Every other week'), ('OTHER', 'Other'), ('NONE', 'Not now, thanks')], default='WKLY', max_length=6)),
                ('challah_number', models.IntegerField(default=1)),
                ('sour_freq', models.CharField(choices=[('WEEK', 'Weekly'), ('2_WKS', 'Every other week'), ('OTHER', 'Other'), ('NONE', 'Not now, thanks')], default='WKLY', max_length=6)),
                ('sour_number', models.IntegerField(default=1)),
                ('corn_freq', models.CharField(choices=[('WEEK', 'Weekly'), ('2_WKS', 'Every other week'), ('OTHER', 'Other'), ('NONE', 'Not now, thanks')], default='WKLY', max_length=6)),
                ('corn_number', models.IntegerField(default=1)),
                ('confirmed', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, max_length=500, null=True)),
                ('this_is_a_gift', models.BooleanField(default=False)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_address', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_city', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_state', models.CharField(choices=[('PA', 'Pennsylvania'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('RI', 'Rhode Island'), ('SC', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='PA', max_length=2, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.Products'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maillist',
            name='recipients',
            field=models.ManyToManyField(to='bread.Subscribers'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='order_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bread.Order'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='payment_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bread.Payment'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gift',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.Order'),
        ),
        migrations.AddField(
            model_name='expense',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.Materials'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='mail_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.MailList'),
        ),
    ]
