# Generated by Django 4.0.1 on 2022-02-21 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='picture',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='picture',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 2, 22)),
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
