# Generated by Django 4.0.1 on 2022-02-24 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0002_alter_category_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='resolution_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 2, 25)),
        ),
    ]
