# Generated by Django 4.0.2 on 2022-02-25 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0003_payment_payment_intent_id_payment_resolution_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('CSH', 'Cash'), ('CHK', 'Check'), ('VEN', 'Venmo'), ('CRD', 'Card'), ('CMP', 'Comped')], max_length=3, null=True)),
                ('payment_intent_id', models.CharField(max_length=234)),
                ('success', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='resolution_date',
        ),
        migrations.DeleteModel(
            name='StripeCharge',
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bread.payment'),
        ),
    ]
