# Generated by Django 4.0.2 on 2022-02-27 04:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bread', '0004_paymentintent_remove_payment_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 3, 1)),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
