# Generated by Django 4.0.2 on 2022-03-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0006_alter_order_delivery_date_shoppingcart_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_message',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
