# Generated by Django 4.0.2 on 2022-03-06 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0008_payment_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 3, 8)),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='success',
            field=models.BooleanField(null=True),
        ),
    ]
