# Generated by Django 4.0.3 on 2022-04-07 02:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bread', '0010_order_ship_this_shipment_ledger_shipment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 4, 8)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 22, 54, 22, 770704)),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField()),
                ('refund_method', models.CharField(choices=[('CSH', 'Cash'), ('CHK', 'Check'), ('VEN', 'Venmo'), ('CRD', 'Card'), ('CMP', 'Comped')], max_length=3)),
                ('refund_id', models.CharField(max_length=234)),
                ('confirmed', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='refund_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bread.refund'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='refund_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bread.refund'),
        ),
    ]
