# Generated by Django 4.0.3 on 2022-09-25 18:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bread', '0012_refund_cart_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 9, 27)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 14, 26, 38, 266920)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='challah_freq',
            field=models.CharField(choices=[('WEEK', 'Weekly'), ('2_WKS', 'Every other week'), ('4_WKS', 'Every four weeks')], default='WKLY', max_length=6),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='corn_freq',
            field=models.CharField(choices=[('WEEK', 'Weekly'), ('2_WKS', 'Every other week'), ('4_WKS', 'Every four weeks')], default='WKLY', max_length=6),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sour_freq',
            field=models.CharField(choices=[('WEEK', 'Weekly'), ('2_WKS', 'Every other week'), ('4_WKS', 'Every four weeks')], default='WKLY', max_length=6),
        ),
        migrations.CreateModel(
            name='ProductSubscription',
            fields=[
                ('index_key', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('frequency', models.CharField(choices=[('WEEK', 'Weekly'), ('2_WKS', 'Every other week'), ('4_WKS', 'Every four weeks')], default='WKLY', max_length=6)),
                ('total_deliveries', models.IntegerField(default=52)),
                ('completed_deliveries', models.IntegerField(default=52)),
                ('confirmed', models.BooleanField(default=False)),
                ('auto_renew', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, max_length=500, null=True)),
                ('this_is_a_gift', models.BooleanField(default=False)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_address', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_city', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_state', models.CharField(choices=[('PA', 'Pennsylvania'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('RI', 'Rhode Island'), ('SC', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='PA', max_length=2, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
